server:
  port: 7002
spring:
  application:
    name: eureka-server2
eureka:
  instance:
    hostname: eureka-server2
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server1:7001/eureka/

